### ISSUE TITLE
list index out of range: while creating a gmsh from a not too large raster

### ISSUE THREAD

**Issue by bhlevca** [jonathanlambrechts/qgis-gmsh#1]
I got this error while processing the mesh

Traceback (most recent call last):
  File "/home/bogdan/.qgis2/python/plugins/gmsh/exportGeometry.py", line 245, in saveGeo
    status = exportGeo(filename, activeLayers, meshSizeLayer, crs)
  File "/home/bogdan/.qgis2/python/plugins/gmsh/exportGeometry.py", line 177, in exportGeo
    geo.addLineFromCoords(geom.asPolygon()[0], xform, lc, physical)
IndexError: list index out of range

**Comment by jonathanlambrechts** [comment]
Hi,
This part of the code has been rewritten. Can you check if the problem persists with the last version available on github ?
Thanks for your repport.

**Comment by bhlevca** [comment]
Hi Jonathan,

I got the plugin from github and tested it . This version works. Perhaps
would be nice if you can update the version from the QGIS plugin repository.

Cheers,
Bogdan

**Comment by bhlevca** [comment]
Hi,

There is one more problem when generating the geo file the plugin
eliminates islands.  Therefore the mesh is not what I really want.

If you want  some screenshots SHP file vs GEO  please let me know.
Otherwise is looking good.

No errors were reported when converting from SHP ->GEO

Thanks
Bogdan

**Comment by jonathanlambrechts** [comment]
Hi,
I will update the official plugin (but I have to found how to do it).
The islands are not supposed to be removed.

Could you send some example ?
If the islands and the external boundaries are on different layers, both 
layers should be selected in the "Mesh Boundary" box.

Jonathan

**Comment by bhlevca** [comment]
I am away from my computer but when I get back I could attach print screen
from the shape file and resulting geo.

No the islands are in the same shape file. I could share my files zipped on
my gdrive for you to test.

Also I noticed that the new version has a extra entry above the mesh size.

Bogdan

**Comment by bhlevca** [comment]
Hi Jonathan,

As promised I am sending you the shape file, and screenshots withe the
shape file, geo file and msh file.

You can see by comparing the shape file with the geo file that all the
islands have been removed.

I am using only one shape file for the Mesh boundaries.

I have another question: what is the "Forced line and points" entry useful
for?

Cheers,
Bogdan

[image: Inline image 1][image: Inline image 2]

**Comment by jonathanlambrechts** [comment]
The images do not appear on Github, could you upload the image and the shapefile somewhere ?
Forced line and points is to force some contours to be present in the mesh (with elements on both sides of the contour).

**Comment by bhlevca** [comment]
I sent all the emails before this one from my email client. This time I am doing from the github page. I hope that you can get them now. The files are all zipped in a single file.

[SHp_FIles_screenshots.zip](https://github.com/ccorail/qgis-gmsh/files/100895/SHp_FIles_screenshots.zip)

**Comment by jonathanlambrechts** [comment]
I think I fixed it, can you try the new version on github ?

**Comment by bhlevca** [comment]
It works properly now on my files. Great work!

What was the problem?
